FROM alpine:3.9

RUN apk update && apk add curl bash

RUN curl -L -o - https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz | tar -zxvf - linux-amd64/helm && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    rm -rf linux-amd64 && \
    chmod +x /usr/local/bin/helm

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    mv kubectl /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

RUN curl -LO https://github.com/openfaas/faas-cli/releases/download/0.8.6/faas-cli && \
    mv faas-cli /usr/local/bin/faas-cli && \
    chmod +x /usr/local/bin/faas-cli

RUN curl -L -o - https://github.com/tsenart/vegeta/releases/download/cli%2Fv12.2.1/vegeta-12.2.1-linux-amd64.tar.gz  | tar -zxvf - vegeta && \
    mv vegeta /usr/local/bin/vegeta && \
    chmod +x /usr/local/bin/vegeta
